### ISSUE TITLE
Image output appears offset, words get cut off

### ISSUE THREAD

**Issue by davidjb** [atizo/PyTagCloud#8]
I've been using the PyTagCloud master from here on GitHub and I've been finding that when attempting to output images, the result ends up frequently cutting words off at the edges -- the output looks like it might be offset from one side.

An example:

![Image](http://i.imgur.com/3PoLK.png)

Note how the left-hand side is a white margin and the word 'respect' gets cut off the at right-hand side.  I've also noticed this happening at the bottom side as well, particularly with words that are longer and vertically aligned.

Snippet of code used to produce this:

```
text = "..."
#Set a max_tags to avoid infinite processing on large word counts
max_tags = 100
tags = make_tags(get_tag_counts(text)[:max_tags], minsize=1,  maxsize=60)
size = (1024, 500)
create_tag_image(tags, 'cloud.png', size=size, fontname='IM Fell DW Pica', layout=LAYOUT_MIX)
```

Am I using something incorrectly?

Thanks for this fantastic library -- extremely helpful.

**Comment by tsiomenko** [comment]
You aren't doing anything wrong, it's a "bug" insomuch that the drawing algorithm does not correctly predict the "center" of the cloud. I've noticed that making maxsize smaller and increasing the number of tags fixes this issue, i.e the less tags there are and the bigger they are, the more pronounced this problem is. However, there is so little documentation, both inside and outside the code, that I'm not sure where to begin fixing the problem.

**Comment by ddexter** [comment]
I am having similar issues. For me, the center is predicted correctly, but the words are not kept in the bounds of the picture. 500x500 with about 100 words ranging from size 6 to 36 font. Thank you for the library!
